## Importing necessary libraries

In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline
plt.style.use('ggplot')

## Getting Datsets from the drive

In [2]:
data=pd.read_csv("concrete_data.csv",sep=',',header=0)
data

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [3]:
data.shape

(1030, 9)

In [4]:
data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
data.isnull().sum()  # no missing value in the dataset

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
# split the data set into predictors (inputs) and target (output)
predictors = data.drop(columns=['Strength'])
target = data['Strength']

n_cols = predictors.shape[1]

In [7]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [8]:
predictors.shape

(1030, 8)

In [9]:
n_cols=predictors.shape[1]
n_cols

8

In [10]:
target.shape

(1030,)

# Part C: Increase no. of epochs=100

Repeat Part B but use 100 epochs this time for training.

How does the mean of the mean squared errors compare to that from Step B?

In [11]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [12]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [13]:
# Data Preparation -PartA
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3,random_state=52)

In [14]:
# build the model
model = regression_model()
model.fit(X_train,y_train,epochs=100,verbose=1)

Epoch 1/100
23/23 [==============================] - 0s 1ms/step - loss: 13718.4170
Epoch 2/100
23/23 [==============================] - 0s 758us/step - loss: 3309.2764
Epoch 3/100
23/23 [==============================] - 0s 746us/step - loss: 2853.1785
Epoch 4/100
23/23 [==============================] - 0s 810us/step - loss: 2505.3384
Epoch 5/100
23/23 [==============================] - 0s 874us/step - loss: 2190.3318
Epoch 6/100
23/23 [==============================] - 0s 830us/step - loss: 1913.3647
Epoch 7/100
23/23 [==============================] - 0s 873us/step - loss: 1659.3058
Epoch 8/100
23/23 [==============================] - 0s 850us/step - loss: 1439.4347
Epoch 9/100
23/23 [==============================] - 0s 790us/step - loss: 1240.6239
Epoch 10/100
23/23 [==============================] - 0s 786us/step - loss: 1070.2427
Epoch 11/100
23/23 [==============================] - 0s 791us/step - loss: 929.9193
Epoch 12/100
23/23 [==============================] - 0s 880us/step - loss: 807.2867
Epoch 13/100
23/23 [==============================] - 0s 815us/step - loss: 711.3604
Epoch 14/100
23/23 [==============================] - 0s 810us/step - loss: 625.9271
Epoch 15/100
23/23 [==============================] - 0s 834us/step - loss: 559.3607
Epoch 16/100
23/23 [==============================] - 0s 875us/step - loss: 511.5796
Epoch 17/100
23/23 [==============================] - 0s 843us/step - loss: 459.7943
Epoch 18/100
23/23 [==============================] - 0s 814us/step - loss: 422.0700
Epoch 19/100
23/23 [==============================] - 0s 891us/step - loss: 393.0771
Epoch 20/100
23/23 [==============================] - 0s 813us/step - loss: 372.7881
Epoch 21/100
23/23 [==============================] - 0s 812us/step - loss: 347.9691
Epoch 22/100
23/23 [==============================] - 0s 901us/step - loss: 334.5269
Epoch 23/100
23/23 [==============================] - 0s 764us/step - loss: 318.0561
Epoch 24/100
23/23 [==============================] - 0s 797us/step - loss: 307.0182
Epoch 25/100
23/23 [==============================] - 0s 856us/step - loss: 294.7616
Epoch 26/100
23/23 [==============================] - 0s 675us/step - loss: 288.8759
Epoch 27/100
23/23 [==============================] - 0s 712us/step - loss: 278.7750
Epoch 28/100
23/23 [==============================] - 0s 882us/step - loss: 271.3883
Epoch 29/100
23/23 [==============================] - 0s 818us/step - loss: 264.6779
Epoch 30/100
23/23 [==============================] - 0s 834us/step - loss: 258.3351
Epoch 31/100
23/23 [==============================] - 0s 885us/step - loss: 254.0064
Epoch 32/100
23/23 [==============================] - 0s 950us/step - loss: 248.1421
Epoch 33/100
23/23 [==============================] - 0s 965us/step - loss: 242.1545
Epoch 34/100
23/23 [==============================] - 0s 877us/step - loss: 241.6657
Epoch 35/100
23/23 [==============================] - 0s 958us/step - loss: 233.8561
Epoch 36/100
23/23 [==============================] - 0s 796us/step - loss: 229.4895
Epoch 37/100
23/23 [==============================] - 0s 806us/step - loss: 229.5984
Epoch 38/100
23/23 [==============================] - 0s 885us/step - loss: 221.1107
Epoch 39/100
23/23 [==============================] - 0s 854us/step - loss: 217.5636
Epoch 40/100
23/23 [==============================] - 0s 834us/step - loss: 217.3877
Epoch 41/100
23/23 [==============================] - 0s 915us/step - loss: 211.3694
Epoch 42/100
23/23 [==============================] - 0s 832us/step - loss: 208.1885
Epoch 43/100
23/23 [==============================] - 0s 826us/step - loss: 202.5680
Epoch 44/100
23/23 [==============================] - 0s 739us/step - loss: 201.0443
Epoch 45/100
23/23 [==============================] - 0s 759us/step - loss: 196.5401
Epoch 46/100
23/23 [==============================] - 0s 742us/step - loss: 192.4918
Epoch 47/100
23/23 [==============================] - 0s 787us/step - loss: 194.6706
Epoch 48/100
23/23 [==============================] - 0s 790us/step - loss: 188.9335
Epoch 49/100
23/23 [==============================] - 0s 735us/step - loss: 184.7659
Epoch 50/100
23/23 [==============================] - 0s 783us/step - loss: 182.4954
Epoch 51/100
23/23 [==============================] - 0s 800us/step - loss: 181.2811
Epoch 52/100
23/23 [==============================] - 0s 807us/step - loss: 178.9639
Epoch 53/100
23/23 [==============================] - 0s 750us/step - loss: 174.3429
Epoch 54/100
23/23 [==============================] - 0s 823us/step - loss: 172.8455
Epoch 55/100
23/23 [==============================] - 0s 769us/step - loss: 169.6144
Epoch 56/100
23/23 [==============================] - 0s 778us/step - loss: 167.9168
Epoch 57/100
23/23 [==============================] - 0s 814us/step - loss: 167.0546
Epoch 58/100
23/23 [==============================] - 0s 764us/step - loss: 164.7600
Epoch 59/100
23/23 [==============================] - 0s 803us/step - loss: 160.7112
Epoch 60/100
23/23 [==============================] - 0s 852us/step - loss: 158.8851
Epoch 61/100
23/23 [==============================] - 0s 788us/step - loss: 161.4068
Epoch 62/100
23/23 [==============================] - 0s 731us/step - loss: 157.8753
Epoch 63/100
23/23 [==============================] - 0s 706us/step - loss: 154.3218
Epoch 64/100
23/23 [==============================] - 0s 678us/step - loss: 154.0993
Epoch 65/100
23/23 [==============================] - 0s 734us/step - loss: 155.5625
Epoch 66/100
23/23 [==============================] - 0s 703us/step - loss: 150.0503
Epoch 67/100
23/23 [==============================] - 0s 725us/step - loss: 147.3805
Epoch 68/100
23/23 [==============================] - 0s 726us/step - loss: 146.7560
Epoch 69/100
23/23 [==============================] - 0s 717us/step - loss: 144.7019
Epoch 70/100
23/23 [==============================] - 0s 707us/step - loss: 142.4996
Epoch 71/100
23/23 [==============================] - 0s 718us/step - loss: 142.1923
Epoch 72/100
23/23 [==============================] - 0s 675us/step - loss: 141.4886
Epoch 73/100
23/23 [==============================] - 0s 715us/step - loss: 138.5779
Epoch 74/100
23/23 [==============================] - 0s 738us/step - loss: 140.1362
Epoch 75/100
23/23 [==============================] - 0s 761us/step - loss: 136.9163
Epoch 76/100
23/23 [==============================] - 0s 701us/step - loss: 135.7787
Epoch 77/100
23/23 [==============================] - 0s 697us/step - loss: 134.9213
Epoch 78/100
23/23 [==============================] - 0s 752us/step - loss: 133.8491
Epoch 79/100
23/23 [==============================] - 0s 789us/step - loss: 134.7016
Epoch 80/100
23/23 [==============================] - 0s 692us/step - loss: 133.1147
Epoch 81/100
23/23 [==============================] - 0s 696us/step - loss: 130.4874
Epoch 82/100
23/23 [==============================] - 0s 752us/step - loss: 131.2352
Epoch 83/100
23/23 [==============================] - 0s 749us/step - loss: 130.3870
Epoch 84/100
23/23 [==============================] - 0s 660us/step - loss: 128.6186
Epoch 85/100
23/23 [==============================] - 0s 788us/step - loss: 130.7081
Epoch 86/100
23/23 [==============================] - 0s 768us/step - loss: 127.5423
Epoch 87/100
23/23 [==============================] - 0s 729us/step - loss: 125.8375
Epoch 88/100
23/23 [==============================] - 0s 638us/step - loss: 129.1973
Epoch 89/100
23/23 [==============================] - 0s 731us/step - loss: 129.8060
Epoch 90/100
23/23 [==============================] - 0s 761us/step - loss: 125.9618
Epoch 91/100
23/23 [==============================] - 0s 725us/step - loss: 125.9300
Epoch 92/100
23/23 [==============================] - 0s 738us/step - loss: 123.7353
Epoch 93/100
23/23 [==============================] - 0s 756us/step - loss: 127.5804
Epoch 94/100
23/23 [==============================] - 0s 693us/step - loss: 124.8158
Epoch 95/100
23/23 [==============================] - 0s 708us/step - loss: 121.0814
Epoch 96/100
23/23 [==============================] - 0s 720us/step - loss: 120.9853
Epoch 97/100

23/23 [==============================] - 0s 706us/step - loss: 121.1534
Epoch 98/100
23/23 [==============================] - 0s 660us/step - loss: 125.0134
Epoch 99/100
23/23 [==============================] - 0s 703us/step - loss: 121.6444
Epoch 100/100
23/23 [==============================] - 0s 729us/step - loss: 119.0710

In [19]:
loss_val = model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)
loss_val

10/10 [==============================] - 0s 923us/step - loss: 49.3595
10/10 [==============================] - 0s 975us/step

49.35951232910156

In [20]:
from sklearn.metrics import mean_squared_error

In [21]:
mean_square_error = mean_squared_error(y_test, y_pred)
mean = np.mean(mean_square_error)
standard_deviation = np.std(mean_square_error)
print(mean, standard_deviation)

49.359505370387204 0.0

### Create a list of 50 mean squared errors and report mean and the standard deviation of the mean squared errors.

In [18]:
total_mean_squared_errors = 50
epochs = 50
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors without normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 101.52006530761719
10/10 [==============================] - 0s 878us/step
MSE 2: 108.862548828125
10/10 [==============================] - 0s 799us/step
MSE 3: 77.8318099975586
10/10 [==============================] - 0s 1ms/step
MSE 4: 77.6663818359375
10/10 [==============================] - 0s 809us/step
MSE 5: 70.36337280273438
10/10 [==============================] - 0s 911us/step
MSE 6: 59.34153747558594
10/10 [==============================] - 0s 922us/step
MSE 7: 59.73200988769531
10/10 [==============================] - 0s 742us/step
MSE 8: 46.07971954345703
10/10 [==============================] - 0s 921us/step
MSE 9: 46.960445404052734
10/10 [==============================] - 0s 1ms/step
MSE 10: 50.715553283691406
10/10 [==============================] - 0s 762us/step
MSE 11: 52.34736251831055
10/10 [==============================] - 0s 886us/step
MSE 12: 45.38217544555664
10/10 [==============================] - 0s 679us/step
MSE 13: 52.863006591796875
10/10 [==============================] - 0s 862us/step
MSE 14: 50.47708511352539
10/10 [==============================] - 0s 1ms/step
MSE 15: 51.85835647583008
10/10 [==============================] - 0s 988us/step
MSE 16: 42.08527755737305
10/10 [==============================] - 0s 918us/step
MSE 17: 48.11195755004883
10/10 [==============================] - 0s 884us/step
MSE 18: 45.88383483886719
10/10 [==============================] - 0s 892us/step
MSE 19: 43.576202392578125
10/10 [==============================] - 0s 871us/step
MSE 20: 47.600704193115234
10/10 [==============================] - 0s 905us/step
MSE 21: 44.46808624267578
10/10 [==============================] - 0s 955us/step
MSE 22: 46.59613037109375
10/10 [==============================] - 0s 1ms/step
MSE 23: 51.63127899169922
10/10 [==============================] - 0s 800us/step
MSE 24: 44.33012390136719
10/10 [==============================] - 0s 840us/step
MSE 25: 49.303653717041016
10/10 [==============================] - 0s 1ms/step
MSE 26: 46.567256927490234
10/10 [==============================] - 0s 786us/step
MSE 27: 46.406639099121094
10/10 [==============================] - 0s 1ms/step
MSE 28: 42.172027587890625
10/10 [==============================] - 0s 893us/step
MSE 29: 52.85049819946289
10/10 [==============================] - 0s 821us/step
MSE 30: 47.72104263305664
10/10 [==============================] - 0s 783us/step
MSE 31: 50.88298034667969
10/10 [==============================] - 0s 1ms/step
MSE 32: 41.1390266418457
10/10 [==============================] - 0s 709us/step
MSE 33: 49.25626754760742
10/10 [==============================] - 0s 825us/step
MSE 34: 67.3877182006836
10/10 [==============================] - 0s 605us/step
MSE 35: 44.15050506591797
10/10 [==============================] - 0s 764us/step
MSE 36: 52.74773406982422
10/10 [==============================] - 0s 829us/step
MSE 37: 51.16497039794922
10/10 [==============================] - 0s 710us/step
MSE 38: 50.63300704956055
10/10 [==============================] - 0s 805us/step
MSE 39: 47.85340881347656
10/10 [==============================] - 0s 1ms/step
MSE 40: 46.992984771728516
10/10 [==============================] - 0s 1ms/step
MSE 41: 49.746402740478516
10/10 [==============================] - 0s 1ms/step
MSE 42: 43.8883171081543
10/10 [==============================] - 0s 879us/step
MSE 43: 50.13917922973633
10/10 [==============================] - 0s 1ms/step
MSE 44: 49.67891311645508
10/10 [==============================] - 0s 722us/step
MSE 45: 54.94871139526367
10/10 [==============================] - 0s 824us/step
MSE 46: 49.148216247558594
10/10 [==============================] - 0s 764us/step
MSE 47: 50.115718841552734
10/10 [==============================] - 0s 1ms/step
MSE 48: 52.83447265625
10/10 [==============================] - 0s 1ms/step
MSE 49: 54.076961517333984
10/10 [==============================] - 0s 773us/step
MSE 50: 49.35951232910156
10/10 [==============================] - 0s 904us/step


Below is the mean and standard deviation of 50 mean squared errors without normalized data. Total number of epochs for each training is: 50

Mean: 53.14902314362195
Standard Deviation: 13.158992234069451

        Peer-graded Assignment 	Mean MSE 	Standard Deviation
    A 	Build a baseline model 	57.64673 	 26.9559	
    B 	Normalize the data      65.75528 	 24.42921	
    C 	Increase the number of epochs (100) 53.14902 	13.15899	
    D 	Increase the number of hidden layers (3) 	? 	?